### PR TITLE
Use ErronoError instead of genericErrors in the lookup function

### LINKED ISSUE #1567: Xeus-cpp-lite fails to include external headers after updating the stack to emsdk 3.1.73
## Description

Xeus-cpp-lite works when when the whole stack is built with emsdk 3.1.45 and packages are fetched from the channel (`https://repo.mamba.pm/emscripten-forge`). Check the static link for the same https://compiler-research.org/xeus-cpp/lab/index.html

But as there is a plan to migrate to a later emsdk (emsdk 3.1.73) and fetch packages out of the newly built channel (`https://prefix.dev/channels/emscripten-forge-dev`), we see errors including external headers. Check https://github.com/compiler-research/xeus-cpp/issues/244

Image

## Reproduce

Build xeus-cpp-lite following the readme instructions (https://github.com/compiler-research/xeus-cpp?tab=readme-ov-file#installation-within-a-mamba-environment-wasm-build-instructions) but with emsdk 3.1.73

## Expected behavior

The include operation should execute successfully as it does with the current static link

## Context

This is what my xeus-lite-host env looks like
```

(xeus-lite-host) anutosh491@Anutoshs-MacBook-Air build1 % micromamba list
List of packages in environment: "/Users/anutosh491/micromamba/envs/xeus-lite-host"

  Name                Version     Build               Channel    
───────────────────────────────────────────────────────────────────
  bzip2               1.0.8       h99b78c6_7          conda-forge
  ca-certificates     2024.12.14  hf0a4a13_0          conda-forge
  cloudpickle         3.1.1       pyhd8ed1ab_0        conda-forge
  doit                0.36.0      pyhd8ed1ab_1        conda-forge
  importlib-metadata  8.6.1       pyha770c72_0        conda-forge
  jupyter_core        5.7.2       pyh31011fe_1        conda-forge
  jupyterlite-core    0.5.0       pyh885dcc9_0        conda-forge
  libexpat            2.6.4       h286801f_0          conda-forge
  libffi              3.4.2       h3422bc3_5          conda-forge
  liblzma             5.6.3       h39f12f2_1          conda-forge
  libmpdec            4.0.0       h99b78c6_0          conda-forge
  libsqlite           3.48.0      h3f77e49_1          conda-forge
  libzlib             1.3.1       h8359307_2          conda-forge
  ncurses             6.5         h5e97a16_2          conda-forge
  openssl             3.4.0       h81ee809_1          conda-forge
  pip                 25.0        pyh145f28c_0        conda-forge
  platformdirs        4.3.6       pyhd8ed1ab_1        conda-forge
  python              3.13.1      h4f43103_105_cp313  conda-forge
  python_abi          3.13        5_cp313             conda-forge
  readline            8.2         h92ec313_1          conda-forge
  tk                  8.6.13      h5083fa2_1          conda-forge
  traitlets           5.14.3      pyhd8ed1ab_1        conda-forge
  tzdata              2025a       h78e105d_0          conda-forge
  zipp                3.21.0      pyhd8ed1ab_1        conda-forge
```

### PR DESCRIPTION
**Pull request by anutosh491**
## References

Fixes #1567 
## Code changes

Discussing with Sam Clegg, the maintainer at emscripten, he says that `genericErrors`, and all the places it is used were removed in 3.1.73 through https://github.com/emscripten-core/emscripten/pull/22914

We should just use `ErrnoError` instead of `genericErrors` if possible !

## User-facing changes

None

## Backwards-incompatible changes

None

### CODE REVIEW

File: packages/contents/src/drivefs.ts [hunk 1]
```diff
@@ -326,7 +326,7 @@ export class DriveFSEmscriptenNodeOps implements IEmscriptenNodeOps {
     const path = this.fs.PATH.join2(this.fs.realPath(node), name);
     const result = this.fs.API.lookup(path);
     if (!result.ok) {
-      throw this.fs.FS.genericErrors[this.fs.ERRNO_CODES['ENOENT']];
+      throw new this.fs.FS.ErrnoError(this.fs.ERRNO_CODES['ENOENT']);
```
Comment (martinRenou) [inline packages/contents/src/drivefs.ts:329]: Neat! Thanks!

Question, was `ErrnoError` also available for old emscripten versions? Or is it a new thing?
So should we detect if `genericErrors` is defined, and use it if it is, with a fallback on `ErrnoError`?

Comment (anutosh491) [reply packages/contents/src/drivefs.ts:329]: Nope, ErrnoError is pretty fundamental as far as I can see and has been there since quite some time.

We actually use it everywhere while throwing (apart from this block)

https://github.com/jupyterlite/jupyterlite/blob/7c67c2e5c3f4734a897652ea18c35244baf30a0f/packages/contents/src/drivefs.ts#L246

https://github.com/jupyterlite/jupyterlite/blob/7c67c2e5c3f4734a897652ea18c35244baf30a0f/packages/contents/src/drivefs.ts#L382

https://github.com/jupyterlite/jupyterlite/blob/7c67c2e5c3f4734a897652ea18c35244baf30a0f/packages/contents/src/drivefs.ts#L473

**Review by martinRenou — APPROVED** [review]
Thanks!

**Comment by martinRenou** [comment]
@meeseeksdev please backport to 0.5.x

**Comment by juntyr** [comment]
jupyterlite-pyodide-kernel also needs a backport since it inlines the jupyterlite code into its worker script (so even though jupyterlite is patched, the current jupyterlite-pyodide-kernel still surfaces the issue)
